=== adannuryusuf/ADSE2509_XML_and_JSON/xsd/employees.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		  elementFormDefault="qualified">
	<!-- Root/Document element: employes -->
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="employee" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="age" type="xs:positiveInteger"/>
							<xs:element name="department" type="xs:string"/>
							<xs:element name="language" type="xs:string"/>
							<xs:element name="salary" type="xs:decimal"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== adannuryusuf/ADSE2509_XML_and_JSON/xml/employees_xsd.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- TODO: link to the employee's xsl file -->
<?xml-stylesheet type="text/xsl" href="../xsl/employee.xslt"?>

<!-- Link to the employee's schema document. -->
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="../xsd/employees.xsd">
	<!-- Employees' Details -->
	<employee>
		<name>John Thorpe</name>
		<age>34</age>
		<department>Marketing</department>
		<language>EN</language>
		<salary>1000</salary>
		<!-- Min. salary supposed to be 1250 -->
	</employee>
	<employee>
		<name>David Blake</name>
		<age>25</age>
		<department>Admin</department>
		<language>GR</language>
		<salary>1200</salary>
	</employee>
	<employee>
		<name>Ben Johns</name>
		<age>28</age>
		<department>Physical Education</department>
		<language>TR</language>
		<salary>800</salary>
	</employee>
	<employee>
		<name>Susan Lopez</name>
		<age>39</age>
		<department>External Affairs</department>
		<language>ES</language>
		<salary>2800</salary>
	</employee>
	<employee>
		<name>Corde Sergio</name>
		<age>32</age>
		<department>Sales</department>
		<language>ES</language>
		<salary>1350</salary>
	</employee>
	<employee>
		<name>Brian John</name>
		<age>27</age>
		<department>Sales</department>
		<language>EN</language>
		<salary>1350</salary>
	</employee>
</employees>
